export const HTTP_STATUS_MESSAGES = {
    100: 'Continue',
    101: 'Switching Protocols',
    102: 'Processing',
    200: 'OK',
    201: 'Created',
    202: 'Accepted',
    203: 'Non-Authoritative Information',
    204: 'No Content',
    205: 'Reset Content',
    206: 'Partial Content',
    207: 'Multi-Status',
    208: 'Already Reported',
    226: 'IM Used',
    300: 'Multiple Choices',
    301: 'Moved Permanently',
    302: 'Found',
    303: 'See Other',
    304: 'Not Modified',
    305: 'Use Proxy',
    306: '(Unused)',
    307: 'Temporary Redirect',
    308: 'Permanent Redirect',
    400: 'Bad Request',
    401: 'Unauthorized',
    402: 'Payment Required',
    403: 'Forbidden',
    404: 'Not Found',
    405: 'Method Not Allowed',
    406: 'Not Acceptable',
    407: 'Proxy Authentication Required',
    408: 'Request Timeout',
    409: 'Conflict',
    410: 'Gone',
    411: 'Length Required',
    412: 'Precondition Failed',
    413: 'Payload Too Large',
    414: 'URI Too Long',
    415: 'Unsupported Media Type',
    416: 'Range Not Satisfiable',
    417: 'Expectation Failed',
    418: 'I\'m a teapot',
    421: 'Misdirected Request',
    422: 'Unprocessable Entity',
    423: 'Locked',
    424: 'Failed Dependency',
    425: 'Too Early',
    426: 'Upgrade Required',
    428: 'Precondition Required',
    429: 'Too Many Requests',
    431: 'Request Header Fields Too Large',
    451: 'Unavailable For Legal Reasons',
    500: 'Internal Server Error',
    501: 'Not Implemented',
    502: 'Bad Gateway',
    503: 'Service Unavailable',
    504: 'Gateway Timeout',
    505: 'HTTP Version Not Supported',
    506: 'Variant Also Negotiates',
    507: 'Insufficient Storage',
    508: 'Loop Detected',
    510: 'Not Extended',
    511: 'Network Authentication Required'
} as const;


export const HEADER_CONTENT_TYPES = {
  text: { 'Content-Type': 'text/plain' },
  html: { 'Content-Type': 'text/html' },
  css:  { 'Content-Type': 'text/css' },
  js:   { 'Content-Type': 'application/javascript' },

  json: { 'Content-Type': 'application/json' },
  form: { 'Content-Type': 'application/x-www-form-urlencoded' },
  multipart: { 'Content-Type': 'multipart/form-data' },

  // images
  png: { 'Content-Type': 'image/png' },
  jpg: { 'Content-Type': 'image/jpeg' },
  jpeg: { 'Content-Type': 'image/jpeg' },
  gif: { 'Content-Type': 'image/gif' },
  webp: { 'Content-Type': 'image/webp' },
  svg: { 'Content-Type': 'image/svg+xml' },
  ico: { 'Content-Type': 'image/x-icon' },

  // documents
  pdf: { 'Content-Type': 'application/pdf' },
  zip: { 'Content-Type': 'application/zip' },
  gzip: { 'Content-Type': 'application/gzip' },

  // video
  mp4: { 'Content-Type': 'video/mp4' },
  webm: { 'Content-Type': 'video/webm' },
  ogg: { 'Content-Type': 'video/ogg' },

  // audio
  mp3: { 'Content-Type': 'audio/mpeg' },
  wav: { 'Content-Type': 'audio/wav' },
  aac: { 'Content-Type': 'audio/aac' },
  oga: { 'Content-Type': 'audio/ogg' },

  // fonts
  woff: { 'Content-Type': 'font/woff' },
  woff2: { 'Content-Type': 'font/woff2' },
  ttf: { 'Content-Type': 'font/ttf' },
  otf: { 'Content-Type': 'font/otf' },

  // binary
  octet: { 'Content-Type': 'application/octet-stream' }
} as const