export const CONTROLLER_METADATA = Symbol("controllers");
export const ROUTE_METADATA      = Symbol("routes");
export const SERVICE_METADATA    = Symbol("services");
export const SWAGGER_METADATA    = Symbol("swaggers");
export const MIDDLEWARE_METADATA = Symbol("middlewares");

// "design:paramtypes" is a metadata key automatically generated by TypeScript 
// when the emitDecoratorMetadata compiler option is enabled. 
// It stores the constructor parameter types of a class and can be accessed through the Reflect Metadata API.
export const PARAMTYPES_METADATA = "design:paramtypes";